import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import { Lato, Raleway, Fredoka, Kanit, Ubuntu, Roboto_Condensed } from 'next/font/google';

const lato = Lato({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-lato' });
const raleway = Raleway({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-raleway' });
const fredoka = Fredoka({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-fredoka' });
const kanit = Kanit({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-kanit' });
const ubuntu = Ubuntu({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-ubuntu' });
const robotoCondensed = Roboto_Condensed({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-roboto-condensed' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lato.variable} ${raleway.variable} ${fredoka.variable} ${kanit.variable} ${ubuntu.variable} ${robotoCondensed.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
